version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=mq_dev
      - RABBITMQ_DEFAULT_PASS=dev_password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648 #for rabbit not to crash mem 2 Gbit
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5673:5672"
      - "15672:15672"
    networks:
      - mynetwork

  website-parser:
    depends_on:
      - rabbitmq
    hostname: website-parser
    build: .
    networks:
      - mynetwork



networks:
  my_network:
    name: my_network
    driver: custom-driver-1