name: Main
on:
  push:
    branches:
      master
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
  #setup
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          architecture: x64

  #build:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  #cacheDependencies:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  #packageWorkflowDataAsArtifacts:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
